apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-monitor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-monitor
  template:
    metadata:
      labels:
        app: video-monitor
    spec:
      containers:
        - name: video-monitor-container
          image: furkan/video_monitor:latest  # ðŸ‘ˆ BurayÄ± doÄŸru docker image ile deÄŸiÅŸtir
          resources:
            limits:
              nvidia.com/gpu: 1  # ðŸ‘ˆ GPU kullandÄ±ÄŸÄ±mÄ±zÄ± belirtiyoruz
          volumeMounts:
            - name: video-volume
              mountPath: /app/video
            - name: logs-volume
              mountPath: /app/logs
      volumes:
        - name: video-volume
          hostPath:
            path: /mnt/video  # ðŸ‘ˆ Worker node Ã¼zerinde buraya yazacak
            type: DirectoryOrCreate
        - name: logs-volume
          hostPath:
            path: /mnt/logs
            type: DirectoryOrCreate
