[project]
name = "yoloproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy==1.26.4",
    "opencv-python==4.8.0.76",
    "tqdm==4.66.1",
    "ultralytics>=8.3.0",
]
